### ISSUE TITLE
Spezifikation des Projektes/Softwareentwurfs

### ISSUE THREAD

**Issue by fb89zila** [fb89zila/exam-repo_swe-sose21#1]
So, um dass hier auch ins rollen zu bringen hab ich mal ein extrem grobes Klassendiagramm gemacht.  
Das sind denke ich mal die grundlegenden Klassen die wir brauchen:
- `MarkdownParser`, um die Markdown-Dokumente einzulesen und zu analysieren
- `MarkdownToLatexTranslator` (temp. Name), um die Daten zu bearbeiten und mit dem `Calculator` zu berechnen
- `LatexRenderer`, um die gewonnenen Daten in ein LaTeX-Format zu bringen und in ein entsprechendes Dokument zu speichern

![structure](https://www.plantuml.com/plantuml/svg/VOzB2e0m34Jtdg9heJSG4TmgY7Y1KEF6s4AIeiTN_8AWk-6z2KmAKM2D4nbHZauZO-88H4mDFFPXzWsm89-m0iMbHTyZt-mgTc6t7OCN0WsNBu5SF43oP6Dj-dFwQOmb73H_p_lkP_QrkjZ2zl0A)

> Wie gesagt, das Diagramm ist sehr grob. Zur eventuellen weiteren Unterteilung und dem hinzufügen anderer Klassen/Vererbungen ist diese Diskussion da.

---

## Weiteres:
- Ich richte ein paar Sachen im Wiki ein, da können wir dann auch wichtige Infos abtragen
- Hab mir überlegt einen Branch einzurichten, um eventuell zu benutzende Dateien abzulegen
- Was Dokus angeht, wir sollten sofort wenn wir anfangen wirklich zu programmieren immer gleich die XML-Dokumentation (diese speziellen Kommentare) führen
- Ob und für was wir eine Testklasse anlegen (z.B. für den Calculator) können wir einzeln besprechen
- Weitere Ideen und Verbesserungen sollten wir bevor wir anfangen hier besprechen und später als einzelne Issues behandeln

**Comment by fb89zila** [comment]
- Wiki Grundstruktur ist fertig
- Hab Branch `material` angelegt, aber vllt. ist es besser sich was anderes zu überlegen, da es als Branch ja immer mit `master` verglichen wird?

**Comment by BerndSchmecka** [comment]
Gefällt mir schon mal sehr gut :+1:  Wegen dem Branch, der wird nur mit dem `master` verglichen, da er sozusagen aus dem `master` hervorgegangen ist. Wenn man manuell über GitHub nen neuen Branch einrichtet, wird der nicht mit dem `master` verglichen, da er dann eine völlig eigenständige Commit-History hat (wie z.B. der `gh-pages` Branch im anderen repo)

EDIT: Unabhängiger Branch geht wohl auch mit `git checkout --orphan <BRANCH_NAME>`

**Comment by fb89zila** [comment]
Hmm vergleicht immer noch, aber egal. ignorieren wir es.

**Comment by BerndSchmecka** [comment]
Ja, eigentlich hätte das nicht mehr passieren sollen, ist aber egal.
Wegen des  `MarkdownParser`s müssten wir uns überlegen, in welcher Form man z.B. Formeln angibt (z.B. einfach in einer ähnlichen Syntax wie bei den Mathe-Tests im OPAL\*) und wie man mit Sonderzeichen wie  `θ`​ umgeht (Ob man die im Markdown dann 1:1 als Zeichen schreibt oder sowas wie `&theta;` als Platzhalter macht (wie bei HTML, eine Liste wäre unter https://www.htmlhelp.com/de/reference/html40/entities/symbols.html zu finden). Soweit ich weiß unterstützt Markdown auch HTML, zumindest kann ich hier in GitHub diese Platzhalter auch verwenden.

\* Das könnte man dann z.B. mit `MathNet.Symbolics.SymbolicExpression.Parse("x^2+y^2+ln(x*y)")` parsen

**Comment by fb89zila** [comment]
Naja, da wir von puren MD-Dokumenten reden können wir nur die `x^2+y^2+ln(x*y)` Variante verwenden.
Für MathJax/LaTeX müsste man mit Javascript arbeiten.

Wenn es direkt die Unicode-Zeichen sind kann es direkt übernommen werden, aber die HTML-Entities können wir auch betrachten.

Sowieso, die erste Version unseres Programms wird noch nicht alles betrachten, was in dem MD passiert. Da können wir dann eventuell noch Updates machen.

**Comment by fb89zila** [comment]
Was wir aber noch klären müssen ist welche Teile von Numerics wir umsetzen. (von Matrizen, Integralen, Differentialen, und was es sonst noch gibt)

**Comment by BerndSchmecka** [comment]
Stimmt, da gibt es ja einiges.
Ich würde vorschlagen, dass wir uns (zumindest am Anfang) auf so "grundsätzliche" Dinge wie z.B. Lineare Gleichungssysteme, Ableitungen, Nullstellen, Eigenwerte/Eigenvektoren oder so beschränken. Bei den Integralen weiß ich nicht, ob man auch unbestimmt integrieren kann (bis jetzt hab ich irgendwie nur was mit oberer/unterer Grenze gefunden).
Aber man könnte ja am Anfang aus nem Markdown-Dokument z.B. ein LGS auslesen (meinetwegen `a*x+b*y = c` und `d*x+e*y = f`, das dann in der Form ![LGS](https://latex.codecogs.com/gif.latex?%5Cbg_white%20%5Cbegin%7Bpmatrix%7D%20a%20%26%20b%5C%5C%20d%20%26%20e%20%5Cend%7Bpmatrix%7D%20*%5Cbinom%7Bx%7D%7By%7D%20%3D%20%5Cbinom%7Bc%7D%7Bf%7D) ausgeben und die Lösung angeben. Oder eine Matrix einlesen und dort einmal das ganze Programm (nxm, Eigenwerte + Eigenvektoren, Determinante, Rang, ...) mit LaTeX Formatiert dann ausgeben. Man müsste sich nur überlegen, wie man dann dem Programm klar macht, welche Stellen im Markdown-Dokument nur Text sind und welche Berechnet werden müssen.

**Comment by fb89zila** [comment]
Also ich hab mal geguckt und die `Numerics.LinearAlgebra` an sich ist denke ich groß genug. Ich weiß nicht ob wir noch groß anderes machen können, ohne dass es zu viel wird oder ob nicht schon das zu viel ist.

Am besten fragen wir dann in der Übung.

**Comment by BerndSchmecka** [comment]
Ja, da wäre ich auch dafür :+1:

**Comment by fb89zila** [comment]
Ok, also nehmen wir nur einfache Funktionen und haben den Hauptfokus auf das Parsen in unserer v1.0.  
Sollte der Umfang geringer als erwartet ausfallen können wir noch eine v2.0 mit einem weiteren Abschnitt aus `Numerics` bearbeiten.

**Comment by BerndSchmecka** [comment]
Finde ich gut, so können wir alles ein bisschen enger eingrenzen und bei Bedarf dann noch erweitern

**Comment by fb89zila** [comment]
Ok, wegen dem UML:

Ich werde bis morgen mal was zusammenschreiben und dann hier reinstellen. Wenn du zusätzlich ein eigenes erstellst umso besser.  
Danach wäre es gut wenn wir morgen Abend (von mir aus nach der Forschungsveranstaltung) in Discord drüber reden.

Das README schreibe ich dann nach dem finalen Klassendiagramm (ich will da drin aufzeigen was genau möglich ist).

**Comment by BerndSchmecka** [comment]
Ja, können wir so machen

**Comment by fb89zila** [comment]
Als nächstes müssen wir noch die Arbeitsteilung bestimmen, da mach ich ein extra Issue auf.
