### ISSUE TITLE
Parameter für gewünschte Ergebnisse in Markdown-Funktionen

### ISSUE THREAD

**Issue by fb89zila** [fb89zila/exam-repo_swe-sose21#10]
Ok ich hatte die Idee mit dem zweiten `switch case` mit falltrough.  
Ich würde sagen wichtig ist besonders wie die Parameter angebracht werden. Also wie die zweite Gruppe des `MatchMathElement()` Matches aussieht.

Wir haben mehrere Optionen:
- `! func!p1,p2,p3,[...]` oder `! func !p1,p2,p3,[...]` (die weiteren schreib ich nur mit Leerzeichen, da ich es übersichtlicher finde)
- `func !{p1}{p2}{p3},[...]`
- `func ![p1][p2][p3],[...]`
- und so weiter

Ich bin für {parameter} mit Leerzeichen vor dem !.
Und jetzt wo ich das so schreibe fällt mir was auf... In `MarkdownParser.MatchMathElement` werde ich ja bestimmt einfach den kompletten Parameterblock Matchen.  
Wenn wir also in `MathParser` ein RegEx schreiben, welches die einzelnen Parameter matched macht es am meisten Sinn `Matches()` zu benutzen und somit eine `MatchCollection` zu bekommen.
Mit `foreach` kann dann über diese iteriert werden und jedes Parameter kann einzeln in das `switch case` geworfen werden --> kein falltrough nötig und es kann einfach auf Gleichheit des Parameterstring getestet werden.

**Comment by BerndSchmecka** [comment]
> Ich bin für {parameter} mit Leerzeichen vor dem !

Können wir gerne so machen.
