### ISSUE TITLE
Parameter-Namen

### ISSUE THREAD

**Issue by fb89zila** [fb89zila/exam-repo_swe-sose21#16]
Da ich jetzt sowieso noch wach bin mach ich mal diese Konvo auf.  
Mir müssen uns noch auf die Namen der Parameter festlegen (auch wenns gerade nur 2 geben wird).

Mein Vorschlag:
- Inputparameter (Auswahlparameter für die mathematischen Markdown-Objekte) 
  - "svfunc" - Funktion mit einer Variable
- Outputparameter
  - "result" - Ergebnis

**Comment by BerndSchmecka** [comment]
Ja, passt so

**Comment by fb89zila** [comment]
Ich mach hier mal zu
