### ISSUE TITLE
Ziel 1.0

### ISSUE THREAD

**Issue by fb89zila** [fb89zila/exam-repo_swe-sose21#18]
Hier können wir beide noch Dinge hinschreiben, welche uns noch auffallen.

**Comment by fb89zila** [comment]
Gleich was:
- Wegen dem neuen Paragraphen `\\\\`, das macht Probleme in Latex --> füg am Anfang des Dokumentes noch `\setlength{\parskip}{1em}` hinzu (nehm bei `\setlength{\parindent}` vllt auch `em` zur Einheitlichkeit, ist allgemein praktisch) und nehm statt `\\\\` `\par`

**Comment by BerndSchmecka** [comment]
Ok, ich habs in #19 mal geändert

**Comment by fb89zila** [comment]
Du hast noch bei `WriteLatexDocument()` den `latex` Unterordner vergessen, wenn man den Markdown Pfad durchgibt.
``` C#
else if (Path.GetExtension(path) == ".md"){
    latexPath = Path.Combine(Path.GetDirectoryName(path), "latex", Path.GetFileNameWithoutExtension(path), ".tex");
```

PS: Ich hab garnicht gelesen, das `Path.Combine()` bis zu 4 Argumente bekommen kann^^

**Comment by fb89zila** [comment]
Oh und ich hab ein extrem komisches Phänomen.  
Wenn ich in `TestMdToTex` weitere Tests hinzufüge (`TestConvertText()`, `TestConvert()` und auch wenn die nichts machen/leer sind) schlagen in `TestLatexRenderer` Tests fehl.  
Ich hab Null Ahnung was hier abgeht.

**Comment by fb89zila** [comment]
Ok nach mehreren Testdurchläufen mit den auskommentierten neuen Tests schlagen welche aus `LatexRenderer` (momentan immer `TestWriteHeadline()`) random fehl oder laufen durch.

Ich hab irgendwie das Gefühl, so komisch wie es auch klingt, das es an der Zeilenanzahl in `TestMdToTex` liegt, auch wenn ich keine Ahnung hab wieso.

**Comment by fb89zila** [comment]
Ich hab eine Theorie. Ich glaube die Tests laufen bei mir(?) multi-threaded. Also kann es vllt. sein das sich in `LatexLines` was überlagert...

**Comment by BerndSchmecka** [comment]
Ok, das könnte natürlich sein und würde auch erklären, warum die random durchlaufen und random nicht.

**Comment by fb89zila** [comment]
Hmm, aber selber wenn ich [das hier](https://xunit.net/docs/configuration-files#parallelizeTestCollections) mache ändert sich nichts...

**Comment by BerndSchmecka** [comment]
Hmm... Bei mir kann ich machen, was ich will, die Tests laufen immer sauber durch, seltsam...
Aber unabhängig davon hab ich gerade noch ein minimales Problem beim LaTeX-Pfad erkannt. Beim Testen der Ausgabe ist mir aufgefallen, dass statt `latex/name.tex` `latex/name/.tex` ausgegeben wird. Da der passende Fix zu klein für einen extra Branch + Pull Request ist, pushe ich den mal direkt in den `master`.

**Comment by BerndSchmecka** [comment]
Jetzt habe ich die Test-Probleme auch... Beim Testen lief `TestWriteLatexDocument()` nicht durch, danach aber ohne irgendwelche Änderungen ca. 10 mal fehlerfrei... Irgendwie müssen wir ne racing condition irgendwo drin haben

**Comment by fb89zila** [comment]
Ich hab echt kein Plan. Vllt ist das sogar CPU abhängig...
![Screenshot (197)](https://user-images.githubusercontent.com/73189649/126172433-7bce9d58-4a25-4640-ae96-9b616bed5a2f.png)

**Comment by fb89zila** [comment]
Es passiert aller ~5-10 (kompletten) Testdurchläufe. Und am meisten in `WriteLatexDocument`, `WriteList` und `WriteQuote`

**Comment by fb89zila** [comment]
Aber besonders in `WriteLatexDocument`

**Comment by BerndSchmecka** [comment]
Jup, genau das gleiche hatte ich auch... Eventuell könnte man ja mittels dieses `ITestOutputHelper` zu Debuggingzwecken sich im `TestWriteLatexDocument` mal die vollständigen Arrays ausgeben lassen, vielleicht werden da random irgendwelche Zeilen vertauscht oder so

```csharp
using Xunit;
using Xunit.Abstractions;

public class MyTestClass
{
    private readonly ITestOutputHelper output;

    public MyTestClass(ITestOutputHelper output)
    {
        this.output = output;
    }

    [Fact]
    public void MyTest()
    {
        var temp = "my class!";
        output.WriteLine("This is output from {0}", temp);
    }
}
```

**Comment by fb89zila** [comment]
Idee: Versuch mal in allen Tests, wo mehrere Zeilen irgendwo hingeschrieben werden (Arrays, List oder sogar Datei) , ein `Thread.Sleep()` (was weiß ich intern (array, etc.) 10ms und Datei >=100ms) nach dem schreiben hinzuzufügen.

**Comment by fb89zila** [comment]
Klingt dumm, aber vllt. asserted das während noch nicht mal fertiggeschrieben wurde.

**Comment by BerndSchmecka** [comment]
Stimmt, die drei von dir genannten, wo das häufig auftritt sind zufällig auch die Tests mit den größten Arrays

**Comment by fb89zila** [comment]
Oder ich hab das mal so gemacht:
``` C#
//act
            foreach (string s in mdLines) {
                MdToTex.convert(s);
            }
            string[] result = LatexRenderer.LatexLines.ToArray();

//assert
            Assert.Equal(expTex, result);
```

Vllt ist das stabiler, da man da mit 2 arrays arbeitet (vllt besser als Thread.Sleep)

**Comment by BerndSchmecka** [comment]
Funktioniert das? Ich kann das leider schlecht einschätzen, da bei mir dieser Fehler nur 3 Mal nach ca. 50 Testdurchläufen vorgekommen ist

**Comment by fb89zila** [comment]
Außer `WriteLatexDocument`, da das die Datei erstellen muss. Da ist vllt ein `Thread.Sleep(1000)` besser.

**Comment by fb89zila** [comment]
Ich probier es gleich

**Comment by BerndSchmecka** [comment]
Ok, ich bau das schon mal in den `fix_tests` Branch mit ein

**Comment by fb89zila** [comment]
Ok jetzt ist es noch schlimmer... (oder vllt ist das gut):  
![Screenshot (199)](https://user-images.githubusercontent.com/73189649/126178565-351b0845-49f1-4a2d-b861-0a496bac00f1.png)

Heute kann ich nicht mehr weiterprüfen (werde bestimmt auch nicht mehr antworten), aber Morgen kuck ich mir das nochmal an.

**Comment by BerndSchmecka** [comment]
Ok, in der Zwischenzeit werde ich auch noch mal überlegen, was das sein könnte

**Comment by fb89zila** [comment]
Ist jetzt übrigens durchgehend

**Comment by fb89zila** [comment]
Ich mach mal einen neuen Branch auf mit meinen Änderungen (auch an an den TestLatexRenderer)

**Comment by fb89zila** [comment]
[debug_tests](https://github.com/fb89zila/exam-repo_swe-sose21/tree/debug_tests)

**Comment by BerndSchmecka** [comment]
Ok, ich glaub ich habs, es ist eine Mischung aus mehrerem Zeug:
* Bei irgend einer Testklasse müssen wir am Dateianfang `[assembly: CollectionBehavior(DisableTestParallelization = true)]` schreiben, um Parallelisierung abzuschalten
* Bei `TestConvertText()` fehlt das `Clear()` der Liste am Anfang
* Und zu guter letzt wird im LatexRenderer `InList` bzw. `InQuote` nach der Liste/Zitat nicht wieder auf 0 gesetzt. In meinem Test habe ich einfach bei `WriteMathElement`, `WriteHeadline`, `WriteText`, `StartNewLine` und `StartNewParagraph` in der ersten Zeile ein `InList = 0; InQuote = 0;` eingefügt, ich weiß aber nicht, ob das die optimale Lösung ist

Nachdem ich alle drei Punkte (provisorisch) behoben habe, hatte ich zuverlässig keine Fehler mehr

**Comment by fb89zila** [comment]
So nach dieser ES-Prüfung, gehts gleich weiter...
Ich probiere es mal aus.

**Comment by fb89zila** [comment]
Zum letzten Punkt. Wie setzt du die auf 0? Die haben doch ein `private set;`.

**Comment by fb89zila** [comment]
Oder meinst du du hast das direkt im `LatexRenderer` gemacht?

**Comment by BerndSchmecka** [comment]
Ja genau, direkt im `LatexRenderer`, in den anderen Write-Methoden (außer bei z.B. Fett und Kursiv, da man ja auch innerhalb einer Liste Fett und Kursiv schreiben will und es einen sonst aus der Liste raushauen würde)

**Comment by fb89zila** [comment]
Fett und Kursiv sind sowieso außen vor, da die nicht in die nächste Zeile springen.
Ich würde sagen am schönsten wäre es eine Methode
``` C#
private static void ResetListOrQuote()
   {
      if (InList > 0) { InList = 0; }
      if (InQuote > 0) { InQuote = 0; }
   }
```

Zu implementieren und die am Anfang von den Methoden die du genannt hast aufzurufen.
Bzw. ich hab das schon gemacht und könnte es commiten wenn du nichts dagegen hast. (oder dir was besseres einfällt)

**Comment by BerndSchmecka** [comment]
Ja, du kannst das ruhig committen, was besseres fällt mir im Moment nicht ein

**Comment by BerndSchmecka** [comment]
Perfekt, ich lösche dann auch gleich den `fix_tests` Branch von mir, da der jetzt obsolet geworden ist

**Comment by fb89zila** [comment]
Jap.  
So, da bleibt eigentlich nur das wirkliche Testen mit verschiedenen Markdown Dokumenten, wenn ich das richtig sehe.

Wenn wir da jeder noch 2 Dateien erstellen haben wir mit der bereits vorhandenen `testAll.md` 5 Stück. Am besten wären etwas größere/längere Dateien mit gemixtem Inhalt (vllt auch gleich welcher der Sinn ergibt).

Wenn wir diese Tests durchbekommen würde ich das Wiki vervollständigen und erst dann das Release v1.0 erstellen.

**Comment by fb89zila** [comment]
Oh und ich muss noch in der `Main()` eine ordentliche Ausgabe für den User einrichten. Hab immer noch meine Debug-Ausgaben drin xD

**Comment by BerndSchmecka** [comment]
Mir ist grad noch was aufgefallen: Die RegEx für Single Variable Functions erkennt keine Klammern, dadurch ist so was wie
`!{svfunc} f(1)=sin(x):x !{result}` nicht möglich

**Comment by fb89zila** [comment]
Ich überlege gerade ob es schlimm wäre einfach alles in der Gruppe mit dem eigentlichen Funktionsterm zu matchen.  
Eigentlich nicht, oder? Oder soll ich nur runde Klammern hinzufügen?

**Comment by BerndSchmecka** [comment]
Eigentlich sollte nix schlimmes passieren, weil bei dem Parsen der Funktion noch ne Exception zwischengeschaltet ist

**Comment by fb89zila** [comment]
Na dann:
``` regex
f\(([a-z]|[\d\.]+)\)=(.*):([a-z])
```

**Comment by fb89zila** [comment]
Ich guck mir deins gleich an, aber was anderes:  
Ich hab [das hier](https://gist.github.com/DanielSWolf/0ab6a96899cc5377bf54) gefunden. Ich weiß nicht ob das in unserem Fall viel bringt, da ich das nicht künstlich mit `Thread.Sleep()` verlängern will so wies im dortigen Program.cs ist.

**Comment by BerndSchmecka** [comment]
Hm, sieht eigentlich ganz schön aus. Ich weiß halt nur nicht, wie man dann am besten die Leiste auffüllen will. In dem Beispielprogramm scheint der ja einfach alle 20ms den Fortschritt um 1% zu erhöhen.

**Comment by fb89zila** [comment]
Ich glaube wir lassen das erstmal weg.  
Mal davon abgesehen: Im letzten Action-Run ist `TestParsePath()` durchgefallen weil ich im `act` vergessen hatte den Latex Pfad zu parsen. Keine Ahnung wie das hier bis jetzt durchgegangen ist, aber ok^^

PS: ich besser das bei mir dann aus

**Comment by fb89zila** [comment]
Ich weiß nicht in wie weit es mit der mangelnden Dokumentation zu `MathNet.Symbolics` geht, aber ist es möglich die Exceptions bei `FuncCalculator.Calculate()` und `FuncCalculator.Convert()` weiter aufzufächern? Oder wenigstens die Exception Message anzeigen.

**Comment by BerndSchmecka** [comment]
Soweit ich gesehen habe, wirft z.B. `Expr.Parse()` nur eine `Exception`, weshalb ich vermute, dass `MathNet.Symbolics` selber keine eigenen Exceptions hat. Aber die Message mit anzeigen lassen kann ich einrichten.

**Comment by fb89zila** [comment]
Wow, ich hab vergessen, dass ich noch gar nicht dein RegEx-fix lokal bei mir hab und wundere mich wieso Funktionen mit Klammern nicht funktionieren :D

**Comment by BerndSchmecka** [comment]
War letztens ähnlich bei mir, als die Listen wieder von Group[3] auf Group[2] zurückgeändert wurden. Da hab ich auch erstmal mich ne halbe Stunde gewundert, bevor ich auf die Idee gekommen bin, den master in meinen Branch zu mergen xD

**Comment by fb89zila** [comment]
Hab jetzt erstmal #24 für die Konsolenausgaben und den Test aufgemacht und merge danach.

**Comment by fb89zila** [comment]
Also ich hatte noch eine Idee, welche mir beim schreiben von Funktionen eingefallen ist.  
Wir können die 1.0 erstmal so wie jetzt veröffentlichen, aber meine Idee ändert schon was recht zentrales (obwohl es kein großer Aufwand sein sollte).

Und zwar:  
Statt in der Funktion `f(x)` das `x` mit einer Zahl zu ersetzen, wieso machen wir das nicht in den Parametern?  
Also `!{result(2)}{result(3.4)}...`

**Comment by fb89zila** [comment]
Das würde es so viel schöner machen, schon von der Syntax her.

**Comment by BerndSchmecka** [comment]
Stimmt, vor allem kann man dann mehrere Ergebnisse auf einmal ausrechnen, was schon ziemlich praktisch wäre

**Comment by fb89zila** [comment]
Das RegEx würde [so](https://regexr.com/621hl) aussehen.

**Comment by fb89zila** [comment]
Da könntest du der `Calculate()` Methode vom `FuncCalculator` im `MdToTex.convertMathElement()` den Parameter übergeben und brauchst die Param-Property nicht mehr.

**Comment by BerndSchmecka** [comment]
Ok, ich mach dafür direkt mal nen Branch auf

**Comment by BerndSchmecka** [comment]
Lassen wir dann die Param-Property im Calculator (für eventuelle andere abgeleitete Calculatoren) oder entfernen wir die ganz?

**Comment by fb89zila** [comment]
Ich hab auch übrigens indirekt getestet was bei Grenzwerten passiert. Siehe meine `rational_functions.md`.

> Lassen wir dann die Param-Property im Calculator (für eventuelle andere abgeleitete Calculatoren) oder entfernen wir die ganz?

Ich würde sagen wir lassen es gleich weg. Wenn irgendwo Parameter durchgegeben werden können wir das wie hier machen.  
Da ich das gerade so sage: Ich versuch den RegEx nochmal ein wenig zu ändern (für eventuelle weitere Parameter), mal sehen ob ichs hinbekomme.

**Comment by BerndSchmecka** [comment]
Ok, übrigens nimmt das RegEx keine negativen Zahlen an

**Comment by fb89zila** [comment]
Ahh... das müssen wir auch extra sehen. Ein string `-1` wird ja geparst, also pack ich den Bindestrich mit dazu

**Comment by fb89zila** [comment]
Ok, das ist das beste was ich hinbekommen habe: [regexr](https://regexr.com/621hl)  
Die Zahlen werden alle in Gruppe 2 gematcht, aber müssen dann bei mehreren nochmal per `String.Split()` bei `,` gesplittet werden.  
Für unsere **svfunc**s ist das egal, da nur die eine Zahl durchkommt, aber in den Multis müssen wir das ganze string-Array konvertieren.

**Comment by BerndSchmecka** [comment]
Ok, ich hätte jetzt theoretisch alle Änderungen, die notwendig wären in den `update_parameters` Branch gepusht

**Comment by fb89zila** [comment]
Ich seh gerade, das man ja ohne die `T Param` das ganze Zeug mit nullable entfernen kann^^

**Comment by BerndSchmecka** [comment]
Hab ich alles in dem Branch gemacht^^

**Comment by fb89zila** [comment]
In `Calculator` ist noch das `#nullable enable` bei mir.

Aber noch was anderes, ich seh gerade das du den den `switch case` im `MdToTex` entfernen musstet. Hättest du was sagen müssen: https://regexr.com/621hl

Gruppe 1 ist wieder nur `result`

**Comment by BerndSchmecka** [comment]
Ok, jetzt sollte wirklich der letzte Verweis auf `nullable` weg sein ;)

Der switch case ist jetzt ebenfalls wieder mit drin

**Comment by fb89zila** [comment]
Nice, machst du einen Pull?

**Comment by BerndSchmecka** [comment]
Jap, kommt sofort

**Comment by fb89zila** [comment]
So ich hoffe mein letzter commit löst das fehlschlagen in `TestParsePath()`...

Was mir beim drüber gucken des Codes noch aufgefallen ist, ist das wir die `precision` bei Calculate garnicht benutzen. Wollen wir die irgendwie an `result` anhängen? also z.B. `result(d)[precision]`?

**Comment by BerndSchmecka** [comment]
Ja, können wir eigentlich machen

**Comment by fb89zila** [comment]
RegEx ist wieder hier https://regexr.com/621hl  
Wie du siehst kann man einen Integer angeben oder die `[]` können leer sein (Gruppe 3 leer) oder fehlen (Gruppe 3 nicht vorhanden)

**Comment by fb89zila** [comment]
Ich könnte es auch so machen, dass Gruppe 3 immer existiert, aber eventuell leer ist (wenn es dir das einfacher macht)

**Comment by fb89zila** [comment]
Das sorgt dann aber irgendwie auch dafür das auch immer eine Gruppe 2 da ist (wenn auch leer)

**Comment by BerndSchmecka** [comment]
Eigentlich müsste das egal sein, weil `int.TryParse()` sowieso nur true gibt, wenn irgend eine Zahl vorhanden ist

**Comment by fb89zila** [comment]
Ok, dann lass ich das so

**Comment by BerndSchmecka** [comment]
Ok, Pull Request kommt gleich rein

**Comment by fb89zila** [comment]
Hast du eine Theorie wieso der `TestParsePath()` immer bei einem Pull Request, aber nicht einem direkten Commits fehlschlägt? Zumindest denke ich das es so ist.

**Comment by BerndSchmecka** [comment]
Könnte es eventuell sein, dass der den `latex` Ordner nicht findet, weil dieser Ordner erst in einem späteren Test erstellt wird?  Also der `TestParsePath` will im `latex` Ordner was machen, dieser wird aber erst bei `TestWriteLatexDocument` erstellt. Im `TestParsePath` wird zwar mit `File.Create(texPath)` versucht die .tex Datei zu erstellen, ich vermute aber, dass das fehlschlägt, weil der Ordner noch nicht erstellt wurde

**Comment by fb89zila** [comment]
Ahh, kann sein. Ich mach was.

**Comment by fb89zila** [comment]
Scheints gewesen zu sein. Ist schon lustig, dass unsere Tests verbugter waren als das eigentliche Programm xD

**Comment by BerndSchmecka** [comment]
Jup xD Hoffen wir mal, dass die jetzt wirklich stabil laufen^^

**Comment by fb89zila** [comment]
Was denkst du, ist es bereit für Gold?

**Comment by BerndSchmecka** [comment]
Ja denke schon, zumindest fällt mir im Moment nix ein, was dagegen sprechen würde

**Comment by fb89zila** [comment]
Also werde ich (vllt. nicht mehr heute) das Wiki vervollständigen und im Anschluss das Release hochladen.

**Comment by BerndSchmecka** [comment]
Ok, dann haben wir Version 1.0 geschafft

**Comment by fb89zila** [comment]
Ich hab auch mal mit **XPlat Code Coverage** geguckt was unsere Tests so abdecken und wir erwischen so ziemlich alles, bis auf die Exception(-pfade), in `LatexRenderer` ein Paar Sachen (nichts Großes, nur ein Paar else-Zweige) und Main() (Welche wir manuell getestet haben)

**Comment by BerndSchmecka** [comment]
Ok, wollen wir da die Sachen, die nicht abgedeckt sind noch hinzufügen oder lohnt es sich nicht, die extra mitzutesten?

**Comment by fb89zila** [comment]
Ich versuch mal was zu machen, warte. Und zu deiner Frage, wir können die schon mit einbauen, die sind jetzt nicht zu kompliziert zu erreichen.

**Comment by fb89zila** [comment]
So, ich hab erst nach Actions dafür gesucht, aber manuell ist es einfacher.  
[Coverage Report auf unseren GH-Pages](https://fb89zila.github.io/exam-repo_swe-sose21/coverage/index.html)

Ich hab das nirgendwo sonst verlinkt, ist einfach ein neuer Ordner auf dem `gh-pages` Branch.  
Wenn du dich um die fehlenden Tests kümmern würdest, würde ich weiter am Wiki schreiben. Wie du die Reports erstellst weißt du oder?

**Comment by BerndSchmecka** [comment]
Jap, wird gemacht

**Comment by fb89zila** [comment]
Ah. Mist.  
Mit neuen Push löscht es den coverage Ordner auf `gh-branches`...

**Comment by fb89zila** [comment]
Ok ich hoffe das löst es jetzt. Hab die Klassen Referenz in einen extra Ordner gesteckt (sieht zugehörige `.yml`) und hab den `coverage` Ordner wieder erstellt. Beim nächsten push sehen wirs^^

**Comment by fb89zila** [comment]
Jetzt ist unser Environment/Deployment schrott xD  
Ich schreib dann noch eine kleine html, so dass man dort auf die Klassenreferenz und den Coverage Report kommt

**Comment by fb89zila** [comment]
[Simple Index-Seite orientiert am Dunklen Github Schema](https://fb89zila.github.io/exam-repo_swe-sose21/)

**Comment by fb89zila** [comment]
Nennen wir die ausführbare Anwendung `mdtotex`? Wäre wichtig für den Konsolenaufruf.

**Comment by BerndSchmecka** [comment]
Ja, der Name klingt vernünftig

**Comment by fb89zila** [comment]
Tests scheinen durchgegangen zu sein.  
Wiki ist geschrieben, kannst du dir das bitte mal durchlesen (+README) um zu schauen ob ich was falsch geschrieben habe/was vergessen habe zu schreiben?

**Comment by BerndSchmecka** [comment]
Jap, mach ich

**Comment by BerndSchmecka** [comment]
Ok, erstmal muss ich sagen, dass alles ziemlich gut beschrieben und dokumentiert ist.

Es gibt im Prinzip nur 2 Dinge, die mir aufgefallen sind:
* Das Klassendiagramm ist nicht ganz aktuell (`Calculate()` hat da noch keine Parameter und `_inlist` bzw. `_inquote` sind noch da)
* Bei der RegEx für den Output-Parameter fehlen in der Description die (optionalen) Gruppen 2 und 3 für die zusätzlichen Angaben bei den Parametern

Ansonsten ist mir nichts weiter aufgefallen und wie gesagt alles sehr gut dokumentiert (Da könnte sich MathNet mal ne Scheibe von abschneiden^^)

**Comment by fb89zila** [comment]
Ah ja, das pass ich noch an. 

Btw ich schliesse auch mal den `material` branch, da wir den eh nie gebraucht haben.

**Comment by fb89zila** [comment]
Ich glaube ich habe alles. Ich guck jetzt mal was ich in das Release reinpacke / wie ich das gestalte.

**Comment by BerndSchmecka** [comment]
Jap, sieht gut aus

**Comment by fb89zila** [comment]
Soo ich mach hier mal zu.
