### ISSUE TITLE
Arbeitsteilung

### ISSUE THREAD

**Issue by fb89zila** [fb89zila/exam-repo_swe-sose21#2]
Wir haben die 4 Klassen:
- MarkdownParser
- MdToTex
- Calculator
- LatexRenderer

Die Verteilung ist aber eher kompliziert.
Ich schätze `MarkdownParser` und `LatexRenderer` haben ungefähr den gleichen Aufwand.  
Nun weiß ich nicht ob `MdToTex` mehr Aufwand machen wird als `Calculator`, aber ich schätze es wird so werden.

Was ich mir vorstellen kann ist, dass derjenige mit weniger Aufwand (wird ja dann beim Code schreiben klar) noch die Test Markdown Dokumente schreibt.

Oder wir wenn der Unterschied zu groß ist können wir die `MdToTex` noch aufteilen nach Funktionen.

**Comment by BerndSchmecka** [comment]
Ja, z.B. könnte man die `convertFunction` Funktion noch demjenigen, der den `Calculator` macht, geben (das würde dann auch thematisch zusammenpassen) und *evtl.* auch die `parsePath` Funktion

**Comment by SebastianZug** [comment]
Hallo zusammen, darf ich sagen, dass ich die Idee noch nicht ganz verstanden habe. Beispielhafter C# Code mit einigen Berechnungen auf der Basis von Math.net wird in Latex überführt. An welcher Stelle kommt Markdown hier ins Spiel?

**Comment by BerndSchmecka** [comment]
Guten Tag, der Plan ist, dass ein Markdown-Dokument mit Überschriften, Listen, Zitaten, Fett- und Kursivschreibungen eingelesen wird. Dieses kann dann auch einfachere Funktionen beinhalten, wobei mithilfe einer Regex geprüft wird, ob es sich um eine Funktion handelt. 
Anschließend soll ggf. die Funktion an einer Stelle berechnet werden (dies wird man dann im Markdown-Dokument angeben können) und ein LaTeX-Dokument erstellt werden, welches einerseits die Überschriften, Listen, etc. enthält (also im Prinzip das ganze Markdown-Dokument in ein LaTeX-Dokument überführt) und andererseits auch die Funktion bzw. deren Lösung.
Somit liegt der eigentliche Fokus zunächst auf der Überführung der Markdown-Dokumente in das LaTeX-Format, wobei jedoch die Berechnung einfacher Funktionen mit integriert wird. 
Der Teil, der die Berechnungen umfasst, wird erweiterbar gestaltet, sodass wir je nach Bedürfnis noch weitere Elemente aus Math.net integrieren können (z.B. Funktionen mit mehreren Veränderlichen, Matrizen, ...)

**Comment by fb89zila** [comment]
Ich denke auch das wir RegEx gut für die Erkennung von den Markdown Elementen benutzen können (besonders Inline Elemente wie Fett-/Kursivschrift)

**Comment by fb89zila** [comment]
> Ja, z.B. könnte man die `convertFunction` Funktion noch demjenigen, der den `Calculator` macht, geben (das würde dann auch thematisch zusammenpassen) und _evtl._ auch die `parsePath` Funktion

Ja ich würde sagen einer kümmert sich um die `MarkdownParser` Klasse und den Großteil von `MdToTex`, da in `MdToTex` das Parsen von Markdown die Grundlage ist.
`Calculator` und `LatexRenderer` ist denke auch ein gutes Paar, plus `convertFunction` und von mir aus auch `parsePath` (obwohl letzteres nicht so dramatisch ist).

Willst du an was bestimmten arbeiten?

**Comment by BerndSchmecka** [comment]
> Calculator und LatexRenderer ist denke auch ein gutes Paar, plus convertFunction und von mir aus auch parsePath

Also ich würde mich gerne um diesen Teil kümmern, wenn das in Ordnung wäre

**Comment by fb89zila** [comment]
Ok, da machen wir das so, beginnend mit dem Release von Aufgabe9. Nächste Woche wird stressig :D

**Comment by fb89zila** [comment]
Wollen wir das Issue hier erstmal auflassen?

**Comment by BerndSchmecka** [comment]
Ja, falls evtl. noch Sachen hinzukommen sollten, könnten wir die hier auch gleich aufteilen

**Comment by fb89zila** [comment]
Hab ein Test-Project mit Test-Klassen für jede der Klassen.
