### ISSUE TITLE
Eventuelle Updates (v1.*)

### ISSUE THREAD

**Issue by fb89zila** [fb89zila/exam-repo_swe-sose21#32]
Das Release ist zwar draußen, aber ich denke da wir noch Zeit haben können wir auch noch kleine Erweiterungen vornehmen.

Hier mal ein Paar Sachen wo ich denke das es nicht zu viel Aufwand macht:
- Das RegEx von `svfunction` braucht ja durch unseren `result()` Parameter die Funktionsklammer nicht mehr für Zahlen, also wieso entfernen wir das `:var` (Gruppe 3) am Ende der Funktion nicht und nehmen die Variable in der Klammer dafür
(Gruppe 1) - [regexr](https://regexr.com/62apt)
- In `StartNewLine()` könnte man noch die 2 Leerzeichen von Markdown am Ende mit `String.TrimEnd()` entfernen
- Markdown Verbatim geht bestimmt gut zu machen da die ` `` ` ziemlich spezielle Zeichen sind und sich so mit `Regex.Replace()` leicht ersetzen lassen ([Latex Version](https://www.overleaf.com/learn/latex/Code_listing)).
&nbsp;  
btw. Codeblöcke mit ``` könnte man auch leicht ersetzen, wenn man festlegt das diese in einer separaten Zeile sind als der eigendliche Code (und Code highlighting brauchen wir ja nicht machen)

Sag erstmal was du davon hältst bzw. sag auch wenn dir noch was einfaches einfällt. Eine Aufteilung der eventuellen Aufgaben kommt danach. (Müssen auch vorsichtig sein, dass es nicht zu viel wird... Mathe naht)

**Comment by BerndSchmecka** [comment]
> Das RegEx von svfunction braucht ja durch unseren result() Parameter die Funktionsklammer nicht mehr für Zahlen, also wieso entfernen wir das :var (Gruppe 3) am Ende der Funktion nicht und nehmen die Variable in der Klammer dafür
(Gruppe 1)

Das halte ich für ne sehr gute Idee, damit beseitigen wir auch ein wenig Redundanz, weil man zur Zeit ja eh die Variable zwei mal angibt, obwohl sie nur einmal gebraucht wird.

> In StartNewLine() könnte man noch die 2 Leerzeichen von Markdown am Ende mit String.TrimEnd() entfernen

Können wir auch machen, dürfte ja ziemlich schnell umsetzbar sein

> Markdown Verbatim geht bestimmt gut zu machen da die `` ziemlich spezielle Zeichen sind und sich so mit Regex.Replace() leicht ersetzen lassen (Latex Version).

Das dürfte von all dem Vorgeschlagenem das schwierigste sein, aber ist prinzipiell auch machbar.

**Comment by fb89zila** [comment]
Das Ding ist, selbst wenn wir die Sachen nicht schaffen ist es nicht so schlimm. v1.0 haben wir ja zumindest.

Um noch ein paar Ideen zu bringen:
- Für die `svfunc` könnten wir noch überlegen die [Nullstelle(n)](https://numerics.mathdotnet.com/api/MathNet.Numerics.RootFinding/Bisection.htm) zu bestimmen, das [differenzieren](https://numerics.mathdotnet.com/api/MathNet.Numerics/Differentiate.htm) und/oder das [integrieren](https://numerics.mathdotnet.com/api/MathNet.Numerics.Integration/GaussKronrodRule.htm#Integrate) (gut das wir beim Output die Möglichkeit haben mehrere Inputs anzugeben, da geht das mit unteren und oberen Grenzen) auszuführen. Btw. für Differentiale kann man sich sogar die abgeleitete Funktion ausgeben lassen, aber das ist denke eher zweitrangig.
- In dem Zusammenhang, wenn wir folgendes machen:
``` C#
public abstract class Calculator<T,U> : ICalculator {

        /// <summary>The element to process.</summary>
        public U Element {get; protected set;}
        
_______________________________________________________________________________


public class FuncCalculator : Calculator<string, Func<double,double>>
```

könnten wir das parsen des Funktionsstrings gleich verallgemeinern und man müsste es nicht in jeder Funktion machen.

**Comment by fb89zila** [comment]
Wenn wir sagen, dass wir all das was ich gesagt hab unter TODO stellen, würde ich dieses Mal gerne mit MathNet arbeiten, also meinen 2ten Kommentar umsetzen.

**Comment by BerndSchmecka** [comment]
Ok, dann würde ich das andere Zeug machen

**Comment by BerndSchmecka** [comment]
Ich hab im Branch `refine_program` diese Sachen
> - Das RegEx von `svfunction` braucht ja durch unseren `result()` Parameter die Funktionsklammer nicht mehr für Zahlen, also wieso entfernen wir das `:var` (Gruppe 3) am Ende der Funktion nicht und nehmen die Variable in der Klammer dafür
> (Gruppe 1) - [regexr](https://regexr.com/62apt)
> - In `StartNewLine()` könnte man noch die 2 Leerzeichen von Markdown am Ende mit `String.TrimEnd()` entfernen

schon eingebaut, Inline Verbatim funktioniert auch schon, allerdings habe ich (da ich kein RegEx Experte bin) die zugehörige RegEx mehr oder weniger "zusammengeschustert" (es klappt, aber höchstwahrscheinlich ist die RegEx ne Katastrophe^^). Außerdem wird im Verbatim weiterhin Markdown (Bold / Cursive) in das LaTeX-Counterpart übersetzt (also würde sowas hier `` `**test**` `` im LaTeX dann als `\verb|\textbf{test}|` gerendert und nicht als `\verb|**test**|` (Mir ist nix eingefallen, wie ich das vermeiden kann, ohne gleich die ganze Zeile auszulassen oder aufwendige/fehleranfällige String.Split()-Konstruktionen aufzubauen)

**Comment by fb89zila** [comment]
- Hab ersten RegEx in den regexr-Link aus dem Wiki geschrieben
- Ich würde nicht sagen Katastrophe, aber viel zu umständlich. [Hier](https://regexr.com/62ciq), schenk ich dir.  
Zum fett und kursiv: Ich hab gerade mal die RegEx für [fett](regexr.com/61nv6) und [kursiv](regexr.com/61nv3) angepasst. Und sorry aber ich hab es geschafft die Gruppe wo immer nur `**` oder `*` drinstand wegzubekommen, also müsstest du das noch anpassen. (btw. was ich gemacht habe ist zu sagen, dass wenn ein ` vor/im/hinter einem fetten/kursiven Element steht, dass dieses nicht im konvertieren von fett/kursiv erkannt wird.)

**Comment by fb89zila** [comment]
Ah, was ich vllt noch sagen sollte. Es scheint du hast versucht auch ``` und `` zu erkennen?  
Die Blöcke sollten wir einzeln betrachten.

**Comment by fb89zila** [comment]
Oder wolltest du ermöglichen, dass wie in Markdown jede Anzahl an ` (solange davor und dahinter gleich viel) gematcht werden?

**Comment by BerndSchmecka** [comment]
Danke^^

> Oder wolltest du ermöglichen, dass wie in Markdown jede Anzahl an ` (solange davor und dahinter gleich viel) gematcht werden?

Jap, das wollte ich eigentlich probieren, aber Hauptsache der einfache ` funktioniert

**Comment by fb89zila** [comment]
Wir legen das einfach so fest.  
Was anderes, zu den Nullstellen:
Da gibt es viele Algorithmen, aber keiner ist wirklich DER Algorithmus.

Der stabilste, wo ich bei besten Outputs geben kann ist [Bisection.FindRoot](https://numerics.mathdotnet.com/api/MathNet.Numerics.RootFinding/Bisection.htm#FindRoot), da die Grenzen dort wirklich fest sind.

Verschiedene andere brauchen auch alle Grenzen, aber nehmen die zum Großteil nur als "Richtlinien".  
[Die hier](https://numerics.mathdotnet.com/api/MathNet.Numerics/FindRoots.htm#OfFunction) macht das ganz gut, aber Ich weiß nicht ob ich lieber statische Grenzen hab mit Ausgabe "No roots found in [a,b]" oder einfach minimal Dynamische mit "No roots found." und Ergebnissen außerhalb gegebener Grenzen.

Was denkst du?

**Comment by BerndSchmecka** [comment]
Hmm... eigentlich würde ich sogar sagen, dass das mit den Grenzen besser ist, öfters interessieren ja einen auch nur Nullstellen in bestimmten Bereichen

**Comment by fb89zila** [comment]
Ich merke auch gerade was... Wenn das so wie geplant weiterläuft schwellt die `MdToTex.convertMathElement()`-Methode extrem an... Ich überlege ob es nicht besser ist eine weitere Klasse für die Schritte im `switch case` anzulegen.

**Comment by fb89zila** [comment]
![Screenshot (202)](https://user-images.githubusercontent.com/73189649/126715158-a3b11151-a82c-4554-8d08-d8b30db8636a.png)

Ist der Output so ok?

**Comment by BerndSchmecka** [comment]
> Ich überlege ob es nicht besser ist eine weitere Klasse für die Schritte im `switch case` anzulegen.

Ja, wäre wahrscheinlich wirklich besser

> Ist der Output so ok?

Ich finds gut, man kann alles Wichtige erkennen

**Comment by fb89zila** [comment]
Neue Klasse `CalcConverter` erstellt und anderes wurde angepasst.  

Ok, da lass ich das so. Und bei einem Fehlschlag des Algorithmus (0 oder mehr als eine Nullstellen im Interval) sag ich einfach "Inside the given bounds either no roots or more than one were found." als Exception und lass die Ausgabe im LaTeX-Dokument aus.

**Comment by BerndSchmecka** [comment]
> Und bei einem Fehlschlag des Algorithmus (0 oder mehr als eine Nullstellen im Interval) sag ich einfach "Inside the given bounds either no roots or more than one were found." als Exception und lass die Ausgabe im LaTeX-Dokument aus.

Jap, das klingt gut

**Comment by fb89zila** [comment]
Ich hab nochmal überlegt, und eigentlich wäre es wäre es ja sinnvoll gleich beim erstellen des `FuncCalculators` die 1. und 2. Ableitung zu bestimmen oder? Wenn das so ist könnten wir auch den `NewtonRaphson` oder `RobustNewtonRaphson` nehmen. Da erkennt es immer die erste Nullstelle im Interval und im Gegensatz zum Bisection funktioniert auch anscheinend die `TryFindRoot()` viel besser.

**Comment by fb89zila** [comment]
https://numerics.mathdotnet.com/api/MathNet.Numerics.RootFinding/RobustNewtonRaphson.htm#TryFindRoot

**Comment by BerndSchmecka** [comment]
Stimmt, das würde es dann auch einfacher machen, die Ableitungen evtl. mit auszugeben
> Btw. für Differentiale kann man sich sogar die abgeleitete Funktion ausgeben lassen, aber das ist denke eher zweitrangig.

**Comment by fb89zila** [comment]
Ok, das Ausgeben der Ableitung wäre etwas komplizierter. Zum rechnen braucht man die als `Func<>`, aber zum ausgeben als `SymbolicExpression`. Und die Verteilung auf 2 Zeilen wäre auch schwer, da alles als ein einziger `string` rauskommt wird alles einfach in `\[ \]` reingesteckt und es kommt Mist raus.  
Mir fallen nur 2 Sachen dazu ein. Getrennte Methoden für die Ableitung und die Berechnung davon **oder** das ausgeben eines `string[]`.

Ich würde sagen ich mach den ersten Vorschlag und mach das per überladenen Methoden. Einmal Parameter `{derivative}` für die Gleichung und noch `{derivative()[]}` für eine Berechnung.

**Comment by BerndSchmecka** [comment]
> Ich würde sagen ich mach den ersten Vorschlag und mach das per überladenen Methoden. Einmal Parameter {derivative} für die Gleichung und noch {derivative()[]} für eine Berechnung.

Klingt gut, so kann der Nutzer dann am Ende auch besser Entscheiden, was er haben will

**Comment by fb89zila** [comment]
Als Parameter `f'()` bzw. `f''()` oder `df()` bzw. `ddf()`?  
Oder hast du noch eine bessere Idee? (`derivative` ist zwar bei der ersten ok, aber sollte irgendwann noch die 2. kommen sieht es blöd aus.)

**Comment by BerndSchmecka** [comment]
Vielleicht auch Analog zur Schreibweise ![2. Ableitung von x^3](https://www.zahlen-kern.de/editor/equations/1bucz.png) dann  `df()`, `d2f()` oder `d^2f()`?

**Comment by fb89zila** [comment]
Dann gleich `d1f()` und `d2f()`? Nur nochmal, es geht um die Parameter im Markdown, deswegen eher nicht `d^2f()`

**Comment by BerndSchmecka** [comment]
Ah ok, im Markdown ist ^ wirklich bisschen ungünstig...
Ja, `d1f()` ist gut, dann sieht man auch gleich, dass es die erste Ableitung ist

**Comment by fb89zila** [comment]
Dann mach ich das so.

**Comment by fb89zila** [comment]
Ich werde mit #33 meine Arbeit hier einstellen. Wenn du bereit bist dein Teil zu pushen, würd ich sagen wir machen Zick.  
Übers Wochenende will ich alles auf Mathe legen.

**Comment by fb89zila** [comment]
Wiki mach ich natürlich noch, aber ich fang nichts neues an.

Btw. was die Versionsnummern angeht. Ich denke wenn eine v2.0 der volle Markdownumfang (Tabellen usw. auch) und eine volle Integration von mehreren Algorithmen im Zusammenhang mit unseren Funktionen mit einer Variable wäre, dann sind wir jetzt mit deinem Inlinecode und(?) den Codeblöcken bei ~v1.2 - ~v1.3 oder was denkst du?

**Comment by BerndSchmecka** [comment]
Die Codeblöcke hab ich noch nicht geschafft, Inline ist aber vorhanden. Da wäre eigentlich v1.2 schon gut. Ich werde noch mal drüberschauen und später dann ein Pull-Request erstellen

**Comment by fb89zila** [comment]
Musst den Block ja auch nicht machen, inline reicht.

**Comment by BerndSchmecka** [comment]
Ok, dann kommt gleich das Pull Request

**Comment by fb89zila** [comment]
So, ein was fehlt noch und das ist der Coverage Report. Hochgeladen ist er schon, aber die pages sind noch nicht Deployed. ich mach da mal eine kleine Action

**Comment by fb89zila** [comment]
Nur finde ich keine Action die einfach nur das macht,,,

**Comment by BerndSchmecka** [comment]
Lässt sich evtl [damit](https://github.com/marketplace/actions/deploy-to-github-pages) was machen? Da kann man wohl nen Ordner angeben, der deployt werden soll

**Comment by fb89zila** [comment]
Ich versuch es mal

**Comment by fb89zila** [comment]
Oder warte, ich glaube es geht auch mit der Action die wir bei der Klassenreferenz benutzen. Hab die glaube nur falsch verstanden.

**Comment by fb89zila** [comment]
Ah, egal ich versuch deins mal

**Comment by fb89zila** [comment]
Die Action läuft irgendwie nicht mal an. Naja ich hab keine Ahnung wie die Pages deployen.

**Comment by fb89zila** [comment]
Aber es ist ein neues Deployment, da von der anderen Action, also der Report ist da.

**Comment by BerndSchmecka** [comment]
Hab gerade rausgefunden, dass das deployment nicht als `push`, sondern als `deployment` gewertet wird (https://docs.github.com/en/actions/reference/events-that-trigger-workflows#deployment)

Ist aber eigentlich auch egal, der neue Report ist jetzt ja da

**Comment by fb89zila** [comment]
Ich lese es mir gleich mal durch.  
Zu der fehlenden Coverage: Da brauchst du ja nur den Verbatim-Test einzubauen.

**Comment by BerndSchmecka** [comment]
Jap, den liefer ich gleich

**Comment by fb89zila** [comment]
[[...]](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site)  
> Note: It can take up to 20 minutes for changes to your site to publish after you push the changes to GitHub. If your don't see your changes reflected in your browser after an hour, see "About Jekyll build errors for GitHub Pages sites."

**Comment by fb89zila** [comment]
Das hier mach ich auch mal zu, da es ja erstmal "fertig" ist.
