### ISSUE TITLE
LatexRenderer

### ISSUE THREAD

**Issue by fb89zila** [fb89zila/exam-repo_swe-sose21#4]
Static class with methods to render a LaTeX document.

**Comment by fb89zila** [comment]
Hier hatte ich auch noch eine Idee.  
Wir haben ja in Markdown "einzeilige" Formatierungen, aber in LaTeX gibt es Dinge wie Listen, welche eröffnet und wieder geschlossen werden müssen.

Wir könnten auch mit der ersten Listenzeile gleich Anfangs- und Endzeile erstellen und dann per Index die Listenzeilen dazwischen einsetzen (da nehmen wir anstatt des `string[]` eine `List<string>` in `LatexRenderer`).  
Meine bools von `Markdownparser` würden da auch besser in `LatexRenderer` passen, da die dort ja zählen.

**Comment by BerndSchmecka** [comment]
Während ich hier gerade an der `LatexRenderer` Klasse arbeite, frage ich mich, ob die ganzen static Methoden nicht alle `void` statt `string` als Rückgabetyp haben sollten, weil jede Zeile ja ohnehin in die `LatexLines` Liste geschrieben wird. Und gerade bei der Liste gibt es ja keine einzelne Rückgabezeile.

**Comment by fb89zila** [comment]
Ja `void` ist auch ok.  
Ich glaube ich hatte das so gedacht, dass du die in `MdToTex` aufrufst und dort den `string` zur Liste hinzufügst, aber ist ja nicht Sinn der Sache :D

**Comment by fb89zila** [comment]
Als ich so an meinem Test für dem `MarkdownParser` gesessen habe ist mir was aufgefallen, also hab ich mal dein `LatexRenderer` angeschaut und... naja da gibt es einiges was ich anbringen möchte:
- Ich werde generell (außer MathElement) immer gleich das `Match` bzw. die `MatchCollection` übergeben,  
`MarkdownParser` hat hier nichts verloren. `string` wahr von Anfang an dumm von mir gewählt
- Zu dem Dateipfad, wir werden das ja bestimmt noch anpassen, aber als default war `../latex` sinnfrei.  
Einfach `latex/` macht mehr Sinn, da es ja die `.md` ja z.B. auf dem Desktop sein können (`../latex` dann im Benutzerverzeichnis)
- Listen:
  - Markdown hat doch nur 3 unterschiedliche ungeordnete Listen-Zeichen
    - hier das letzte
      - das ist gleich dem letzten
- Nun zum eigendlichen: Bold/Cursive
  - Ich plane **immer** erst fett und dann kursiv zu ersetzen, da es ja verschachtelt sein kann (erst fett, dann kursiv funkt. am besten), aber mir ist aufgefallen dass das so nichts wird.  
  Wenn es geht, könnten wir wieder zurückwechseln, so das die Methoden (am besten gleich alle) wieder `strings` zurückgeben? `LatexRenderer` sollte doch lieber nur rendern :D

Ich hab jetzt nur auf Sachen geguckt die mich interessieren, genauer guck ich erst beim Review.

**Comment by BerndSchmecka** [comment]
* Ok, dass die Funktionen direkt das Match bekommen, ist natürlich besser und lässt sich eigentlich bei allen Funktionen umsetzen, nur bei Kursiv/Fett könnten wir da Probleme bekommen, weil die `MatchCollection` ja nicht den ganzen Text beinhaltet, sondern nur die fetten/kursiven Anteile
* Ja, mit dem Dateipfad hast du recht, ich passe das an
* Wegen den Lists, die haben doch glaube ich in LaTeX doch eh alle das gleiche Zeichen, das `InList` geht nur bis zur 4, um die Listen bis zur Ebene 4 verschachteln zu können
* Ja, `string` zurückgeben wäre wirklich besser. Aber leider geht das bei allen Funktionen bis auf `Lists/Quotes`, weil es da schwierig ist, die Zeilenweise zu verarbeiten und ich in der Funktion selbst schon mit der `LatexLines` Liste und diversen Lambdas arbeite. Aber vielleicht denke ich einfach nur zu kompliziert ;D

**Comment by fb89zila** [comment]
> weil die MatchCollection ja nicht den ganzen Text beinhaltet, sondern nur die fetten/kursiven Anteile  
 
Ich glaube wir müssen hier nochmal von Anfang an denken. Ich hab das erst im Test wirklich gemerkt, aber für das ersetzen Teilen eines `strings` braucht man die Matches nicht (oder eher sie sind nutzlos, da nicht anwendbar),

 Also folgende Idee:  
`Replace()` funktioniert wie folgt `outputstr = MarkdownParser.TextRx["bold"].Replace(inputstr, @"\textbf{$2}");`  
Das lässt sich leider nicht aufteilen in *erkenne Markdown* und *schreibe LaTeX*, aber ich hab die RegEx ja schon definiert. Wenn ich jetzt also einfach meine Match-Methoden "weglasse", da sie obsolet sind, kann im `LatexRenderer` einfach die `WriteCursive()` & `WriteBold()` `Replace()` wie oben durchführen. Zudem hab ich noch [das hier](https://stackoverflow.com/questions/8728593/can-you-chain-the-result-of-one-delegate-to-be-the-input-of-another-in-c) gefunden. Wenn du also einfach die Methoden erstellst, kann ich so eine `Func` in `MdToTex` implementieren.

> Listen in LaTeX doch eh alle das gleiche Zeichen

Mir gehts nicht um die Zeichen, ich meine das doch eh kaum jemand 4fach verschachtelte Listen nimmt. Es reichen 3 (0 level - list, 1 level - sublist, 2 level - subsublist).

> allen Funktionen bis auf `Lists/Quotes`

Ja eigendlich ist es auch egal. Solange ich bei fett/kursiv die strings bekomme ist das andere egal. Also lass alle Methoden bis auf `WriteCursive()` & `WriteBold()` einfach so. Mit der oben erwähnten `Func` währe es mir möglich eine gute Verkettung zu realisieren.

**Comment by BerndSchmecka** [comment]
> Mir gehts nicht um die Zeichen, ich meine das doch eh kaum jemand 4fach verschachtelte Listen nimmt. Es reichen 3 (0 level - list, 1 level - sublist, 2 level - subsublist).

Achso, ja, stimmt, keine Ahnung, wieso ich 4 gemacht habe. Ich reduziere das mal auf 3

> Also lass alle Methoden bis auf `WriteCursive()` & `WriteBold()` einfach so. 

Ok, ich kümmer mich drum

EDIT: Die anderen Funktionen sollen dann weiterhin einen `string` bzw. ein `Match` als Input bekommen? Gerade bei der Headline muss ich ja dann die Länge der Group[1] auslesen, um zu entscheiden, welche Art der Headline die Richtige ist

**Comment by fb89zila** [comment]
Zum EDIT:

Ja, sorry hab mich nicht genau genug ausgedrückt.
- Bold/Cursive: `input: string` `output: string`
  - Bei dir in `LatexRenderer` wird **nur** mit obrigen `Regex.Replace()` die jeweiligen fetten bzw. kursiven Textstellen ersetzt.
  - Ich verknüpfe die Methoden dann bei mir
- Andere: `input: Match` `output: void` --> wird direkt `LatexLines.Add()`

**Comment by fb89zila** [comment]
Weil ich gerade einen komischen commit von dir gesehen (& kommentiert, wenn du das siehst) habe.  
Im Listen Match ist der Text jetzt in Gruppe 3. Nur nochmal als Anmerkung.

**Comment by fb89zila** [comment]
Mit ist beim Activity Diagram gerade noch auf gefallen das hier noch 3 kleine Methoden fehlen.
- `StartNewParagraph()` - Add("\\\\\\\\")
- `StartNewLine(string line)` - line + "\\\\"
- `WriteText(string line)` - line

EDIT: Zur Erinnerung, `NewParagraph` ist wenn ich eine leere Zeile habe (nichts zu übergeben). `NewLine` wenn am Ende eines normalen Textes zwei Leerzeichen sind und das letzte ist normaler Text

**Comment by BerndSchmecka** [comment]
Ok danke, die füge ich noch hinzu
