### ISSUE TITLE
MdToTex

### ISSUE THREAD

**Issue by fb89zila** [fb89zila/exam-repo_swe-sose21#5]
Main class of project.  
Uses the `MarkdownParser`, `LatexRenderer` and `Calculator` classes to convert Markdown documents to LaTeX documents.

**Comment by fb89zila** [comment]
`convertFunction()` and `parsePath()` are to be implemented by @BerndSchmecka

**Comment by fb89zila** [comment]
Während ich gestern an meinen RegEx's gebastelt habe (naja Großteils bold/cursive) ist mir ein paar was aufgefallen.

Bezüglich Überschriften:  
In LaTeX gibt 3 "normale" Überschriften (nicht Titel), also hab ich mir gedacht  
--> \chapter{#} & \section*{##} & \subsection*{###}

Listen/Unterlisten:
Wegen der Art wie Listen in LaTeX behandelt werden hab ich mir gedacht, dass wir die Listen und Unterlisten zusammenführen. Es gibt maximal 4 Ebenen in LaTeX. anstatt einer `bool inList` wäre es also vllt besser ein `byte inList` zu nehmen und sagen
- 0 -> nicht in Liste
- 1 -> Ebene 1
- 2 -> Ebene 2
- 3 -> Ebene 3
- 4 -> Ebene 4

Zitaten:
Zuletzt ist es hier ähnlich wie bei den Listen, da man Zitate ineinanderlegen kann. Aber hier ist es denke ich nicht sinnvoll 4+ Ebenen zu betrachten, also denke ich 3 Ebenen reichen (auch wenn selbst das keiner macht).

## Zum Schluss:
Ich werde dann gleich noch meine RegEx in das Wiki stellen und dazuschreiben wie ich die Gruppen verwenden werde. Ist für dich in der `LatexRenderer` Klasse wichtig. Wenn du Anmerkungen hast sag Bescheid.

**Comment by BerndSchmecka** [comment]
Ok perfekt, dass die Gruppen so gut aufgeschlüsselt sind :D Anmerkungen hab ich noch keine, falls welche auftreten sollten, schreib ich das hier

**Comment by fb89zila** [comment]
Werd auch noch ein paar Änderungsideen in #3 einbringen.

**Comment by fb89zila** [comment]
Nebenbei, wie weit bist du mit der `parsePath()` Methode?  
Wenn du noch nicht angefangen hast würde ich die machen, da ich sie brauche.

**Comment by BerndSchmecka** [comment]
Die hab ich tatsächlich noch nicht angefangen

**Comment by fb89zila** [comment]
Gut da übernehm ich die. Die `Calculator` Klassen scheinen ja komplizierter zu werden, also muss ich dir am Ende vllt. sogar bei deinen Klassen helfen xD

**Comment by fb89zila** [comment]
Ok, also jetzt ist was passiert. Unser `Calulator calc` Feld funktioniert nicht mehr da es nicht Generic angelegt werden kann.  
Fällt dir was ein?  

Notfalls müssen wir es jeweils als Variable in dem Klassen `switch case` erstellen.

**Comment by fb89zila** [comment]
Interface!
Kannst du bitte ein kleines update machen und
``` C#
public interface ICalculator 
{
    public string ConvertElement();
}
```

erstellen?

**Comment by fb89zila** [comment]
Habs auch im [Klassendiagramm](https://github.com/fb89zila/exam-repo_swe-sose21/wiki/Developer#class-diagram-) eingebracht. Damit ist die Polymorphie gesichert.

**Comment by fb89zila** [comment]
Oder weißt du was ich bring es schnell ein.

**Comment by fb89zila** [comment]
Ich hab gerade an Tests in `MdToTex` gearbeitet und festgestellt das alles private war.  
Ich habs im Klassendiagramm schon angepasst, aber ich hab die jetzt `internal` gemacht und die mit einem assembly-Argument 

``` C#
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("MarkdownToLatex.Test")]

namespace MarkdownToLatex {}
```

für die Tests sichtbar gemacht.

**Comment by BerndSchmecka** [comment]
`[assembly: InternalsVisibleTo("MarkdownToLatex.Test")]`

Sowas gibt's? Das ist echt praktisch

**Comment by fb89zila** [comment]
Hab ich auch nur nach ner viertel Stunde suchen in einem Stackoverflow Post gefunden.

**Comment by fb89zila** [comment]
Was anderes. Ich hab gerade was realisiert.  
`convert()`, `convertText()` und `convertMathElement()` hatte ich alle mit Return-Typ `string` versehen, aber sowohl in `convertMathElement()` und `convertText()` kann/muss man den String welchen man dort erhält ja gleich an `LatexRenderer` Methoden schicken. Also können die eigendlich alle `void` sein.

**Comment by BerndSchmecka** [comment]
Ja stimmt, an sich müssen die ja nix returnen

**Comment by BerndSchmecka** [comment]
Ist es eigentlich beabsichtigt, dass ich in `convert(string line)` an die `convertMathElement(string element)` nur Group[1] von dem Match bekomme? Ansonsten würde ich das so ändern, dass ich das gesamte match bekommen würde.

**Comment by fb89zila** [comment]
Mach. Das ist noch ein Überbleibsel davon wo wir die Parameter noch nicht hatten.
