### ISSUE TITLE
Calculator & MathParser

### ISSUE THREAD

**Issue by fb89zila** [fb89zila/exam-repo_swe-sose21#6]
Class which (for now) calculates simple one line functions

**Comment by fb89zila** [comment]
Ich hatte hier noch eine Idee.  
Da wir das ja erweiterbar machen wollen, wieso nicht eine abstrakte `Calculator` Klasse und dann z.B. `FuncCalculator`?

**Comment by BerndSchmecka** [comment]
Finde ich gut 👍

**Comment by fb89zila** [comment]
`MathParser` Ist dafür da, festzustellen um welche Art von mathematisches Objekt/Element es sich handelt.

**Comment by BerndSchmecka** [comment]
Vielleicht hier noch mal die kurze Rückfrage.
Ich hab die Calculator-Klassen (`Calculator`, `SingleVarCalculator` und `FuncCalculator`) angelegt und dabei ist mir aufgefallen, dass die Properties `Element`, `Variable` und `Input` nie genutzt werden, da ja über die `ConvertElement` Funktion diese Werte direkt übergeben werden.
Brauchen wir die dann noch oder soll ich die zu Beginn der `ConvertElement`-Funktion oder im Konstruktor trotzdem zuweisen (obwohl das dann keinen Sinn ergäbe, da die `ConvertElement`-Funktion diese Werte eh übergeben haben will)?

**Comment by fb89zila** [comment]
Hmm stimmt. Wenn in `MdToTex.convertMath()` das `Match` von `MathParser.MatchSVFunction()` (Also wie bei mir mit dem Rückgabewert angepasst) sowieso zwischengespeichert wird und die nach Datentyp geparsten Gruppen vom `FuncCalculator` direkt berechnet werden, kann man gleich alles angeben.

Aber was machen wir dann mit der Vererbung? Gibt es dann noch irgendwas, was in Calculator zentral ist?  
Ich ess jetzt erstmal und denke währenddessen drüber nach.

**Comment by BerndSchmecka** [comment]
Ok, ich hab vor allem deshalb gefragt, weil dann der `Calculator` komplett leer wäre und der `SingleVarCalculator` nur die zwei abstrakten Methoden beinhalten würde

**Comment by fb89zila** [comment]
Ok, nochmal genauer was die `Calculator` Klassen machen (eventuell sollen):
- Berechnung von Gleichungen & Funktionen
- Umsetzung gewisser mathematischer Algorithmen (Numerics) / Dinge wie Kurvendiskussion
- Wandlung der Eingabe + Ergebnis in LaTeX string

### Zuerst nochmal ein grober Ablauf:
1. Objekt zur gematchten Art von math. Element erstellen
2. `ConvertElement()`-Methoden je nach geparstem Element
3. Die eigendliche Konvertierung
    1. Berechnung der möglichen Eigenschaften/Algorithmen mit gegebenen Input
    2. .ToLatex()

### Bei der Berechung:
Also wenn wir eine Ein-Variablen-Funktion reingeben könnte man ja bei der Erweiterung einfach Properties hinzufügen welche dann immer so weit wie möglich gesettet werden.  
Am Ende einer mathematischen Markdown Zeile könnten wir Argumente abverlangen (z.B. in Form: ` !<Para1>[Para2]...`) welche angeben welche Ergebnisse man haben möchte. Und da wäre es denke mal gut wenn wir das Element in der `ConvertElement()` Methode in die Property speichern.

Außerdem gibt es vllt noch weitere zentrale Dinge die uns jetzt vllt nur noch nicht einfallen.

**Comment by BerndSchmecka** [comment]
Ok, ich hab jetzt die Properties in der `ConvertElement` Methode gesetzt
